import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Footer from "@/components/layout/Footer";
import QueryProvider from "@/context/reactQuery";
import "./globals.css";
import Navbare from "@/components/layout/navbare/Navbare";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="antialiased">
        <QueryProvider>
          <main className="flex min-h-screen flex-col bg-purple-200">
            <Navbare />
            <section className="flex flex-1 flex-col">{children}</section>
            <Footer />
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
