import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Navebare from "@/components/Navebare";
const inter = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={inter.className}>
          <main className="h-screen grid grid-rows-[46px_auto_46px] md:grid-rows-[66px_auto_46px]">
            <Navebare />
            <section className="relative bg-slate-200">
              <div className="shadow-custom-shadow absolute top-0 left-0 right-0 h-32 bg-[#623af3]"></div>
              <div className="relative">{children}</div>
            </section>
            <Footer />
          </main>
        </body>
      </SessionProvider>
    </html>
  );
}

const Footer = () => {
  return (
    <section className="relative text-white flex items-center justify-center bg-[#353131] truncate">
      @ Rights Reserved
    </section>
  );
};
