import type { Metadata } from "next";
import { Signika_Negative, Geist } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import QueryProvider from "@/context/reactQuery";
import { cn } from "@/lib/utils";
import "./globals.css";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inter = Signika_Negative({
  weight: ["300", "400", "500", "700"],
  // weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={inter.className}>
        <QueryProvider>
          <main className="flex min-h-screen flex-col bg-purple-200">
            <Navbar />
            <section className="flex flex-1 flex-col">{children}</section>
            <Footer />
          </main>{" "}
        </QueryProvider>
      </body>
    </html>
  );
}
