import { INearbyAttractionDoc } from "@/types/types";
import { model, Model, models, Schema } from "mongoose";

const nearbyAttractionSchema: Schema<INearbyAttractionDoc> =
  new Schema<INearbyAttractionDoc>({
    name: { type: String, required: true },
    type: { type: String, required: true },
    country: { type: String, required: true },
    createdAt: { type: Date, default: Date.now },
  });

const NearbyAttraction: Model<INearbyAttractionDoc> =
  models.NearbyAttraction ||
  model<INearbyAttractionDoc>("NearbyAttraction", nearbyAttractionSchema);

export default NearbyAttraction;

// const DummyNearbyAttractions = [
//   { name: "Statue of Liberty", type: "Landmark", country: "United States" },
//   { name: "Grand Canyon", type: "Natural Wonder", country: "United States" },
//   {
//     name: "Yellowstone National Park",
//     type: "National Park",
//     country: "United States",
//   },
//   {
//     name: "Hollywood Walk of Fame",
//     type: "Entertainment",
//     country: "United States",
//   },
//   { name: "Times Square", type: "Landmark", country: "United States" },
//   { name: "Mount Rushmore", type: "Historic Site", country: "United States" },
//   {
//     name: "Empire State Building",
//     type: "Skyscraper",
//     country: "United States",
//   },
//   { name: "Golden Gate Bridge", type: "Landmark", country: "United States" },
//   { name: "Niagara Falls", type: "Natural Wonder", country: "United States" },
//   { name: "Walt Disney World", type: "Theme Park", country: "United States" },
//   { name: "Las Vegas Strip", type: "Entertainment", country: "United States" },
//   {
//     name: "Yellowstone Lake",
//     type: "Natural Wonder",
//     country: "United States",
//   },
//   { name: "Smithsonian Institution", type: "Museum", country: "United States" },
//   { name: "Central Park", type: "Park", country: "United States" },
//   { name: "The White House", type: "Historic Site", country: "United States" },
//   { name: "Alcatraz Island", type: "Historic Site", country: "United States" },
//   {
//     name: "Universal Studios Hollywood",
//     type: "Theme Park",
//     country: "United States",
//   },
//   { name: "Lincoln Memorial", type: "Monument", country: "United States" },
//   {
//     name: "Bryce Canyon National Park",
//     type: "National Park",
//     country: "United States",
//   },
//   { name: "Mount Denali", type: "Natural Wonder", country: "United States" },
//   {
//     name: "Chicago Navy Pier",
//     type: "Entertainment",
//     country: "United States",
//   },
//   { name: "The Getty Center", type: "Art Gallery", country: "United States" },
//   {
//     name: "Fisherman's Wharf",
//     type: "Entertainment",
//     country: "United States",
//   },
//   { name: "San Diego Zoo", type: "Zoo", country: "United States" },
//   { name: "National Mall", type: "Landmark", country: "United States" },
//   { name: "Space Needle", type: "Observation Deck", country: "United States" },
//   { name: "Louvre Museum", type: "Museum", country: "United States" },
//   {
//     name: "Sedona Red Rocks",
//     type: "Natural Wonder",
//     country: "United States",
//   },
//   {
//     name: "Statue of Liberty Museum",
//     type: "Museum",
//     country: "United States",
//   },
//   { name: "Glen Canyon Dam", type: "Historic Site", country: "United States" },
//   { name: "Freedom Trail", type: "Historic Site", country: "United States" },
//   {
//     name: "Philadelphia Museum of Art",
//     type: "Art Gallery",
//     country: "United States",
//   },
//   {
//     name: "Grand Teton National Park",
//     type: "National Park",
//     country: "United States",
//   },
//   { name: "The Broad Museum", type: "Art Gallery", country: "United States" },
//   {
//     name: "The National WWII Museum",
//     type: "Museum",
//     country: "United States",
//   },
//   {
//     name: "Santa Monica Pier",
//     type: "Entertainment",
//     country: "United States",
//   },
//   { name: "Hollywood Sign", type: "Landmark", country: "United States" },
//   {
//     name: "Cleveland Museum of Art",
//     type: "Art Gallery",
//     country: "United States",
//   },
//   { name: "Biltmore Estate", type: "Historic Site", country: "United States" },
//   {
//     name: "New Orleans French Quarter",
//     type: "Historic Site",
//     country: "United States",
//   },
//   {
//     name: "Washington National Cathedral",
//     type: "Historic Site",
//     country: "United States",
//   },
//   { name: "The Alamo", type: "Historic Site", country: "United States" },
//   {
//     name: "Muir Woods National Monument",
//     type: "National Park",
//     country: "United States",
//   },
//   { name: "Naples Pier", type: "Landmark", country: "United States" },
//   {
//     name: "Louisville Mega Cavern",
//     type: "Entertainment",
//     country: "United States",
//   },
//   { name: "Pearl Harbor", type: "Historic Site", country: "United States" },
//   {
//     name: "Chicago Art Institute",
//     type: "Art Gallery",
//     country: "United States",
//   },
//   {
//     name: "Carlsbad Caverns",
//     type: "Natural Wonder",
//     country: "United States",
//   },
//   {
//     name: "Catoctin Mountain Park",
//     type: "National Park",
//     country: "United States",
//   },
//   {
//     name: "Cape Cod National Seashore",
//     type: "National Park",
//     country: "United States",
//   },
//   {
//     name: "National Gallery of Art",
//     type: "Art Gallery",
//     country: "United States",
//   },
//   { name: "SeaWorld Orlando", type: "Theme Park", country: "United States" },
//   {
//     name: "Washington D.C. Botanical Garden",
//     type: "Garden",
//     country: "United States",
//   },
//   { name: "Graceland", type: "Historic Site", country: "United States" },
//   { name: "The Exploratorium", type: "Museum", country: "United States" },
//   { name: "Luray Caverns", type: "Natural Wonder", country: "United States" },
//   { name: "MoMA", type: "Art Gallery", country: "United States" },
//   {
//     name: "American Museum of Natural History",
//     type: "Museum",
//     country: "United States",
//   },
//   {
//     name: "Zion National Park",
//     type: "National Park",
//     country: "United States",
//   },
//   {
//     name: "Fort Sumter National Monument",
//     type: "Historic Site",
//     country: "United States",
//   },
//   {
//     name: "Cleveland Botanical Garden",
//     type: "Garden",
//     country: "United States",
//   },
//   {
//     name: "Sequoia National Park",
//     type: "National Park",
//     country: "United States",
//   },
//   {
//     name: "Bunker Hill Monument",
//     type: "Historic Site",
//     country: "United States",
//   },
//   { name: "Denver Botanic Gardens", type: "Garden", country: "United States" },
//   { name: "Mount Vernon", type: "Historic Site", country: "United States" },
//   { name: "Hersheypark", type: "Theme Park", country: "United States" },
//   { name: "The Henry Ford Museum", type: "Museum", country: "United States" },
//   {
//     name: "San Francisco Cable Cars",
//     type: "Historic Site",
//     country: "United States",
//   },
//   {
//     name: "Saguaro National Park",
//     type: "National Park",
//     country: "United States",
//   },
//   {
//     name: "St. Louis Gateway Arch",
//     type: "Landmark",
//     country: "United States",
//   },
//   { name: "Brooklyn Bridge", type: "Landmark", country: "United States" },
//   {
//     name: "Great Smoky Mountains National Park",
//     type: "National Park",
//     country: "United States",
//   },
//   {
//     name: "Aquarium of the Pacific",
//     type: "Aquarium",
//     country: "United States",
//   },
//   { name: "Lake Tahoe", type: "Natural Wonder", country: "United States" },
//   { name: "Guggenheim Museum", type: "Art Gallery", country: "United States" },
//   {
//     name: "Redwood National and State Parks",
//     type: "National Park",
//     country: "United States",
//   },
//   {
//     name: "Franklin D. Roosevelt Presidential Library",
//     type: "Museum",
//     country: "United States",
//   },
//   {
//     name: "Dallas Arboretum and Botanical Garden",
//     type: "Garden",
//     country: "United States",
//   },
//   {
//     name: "National Museum of American History",
//     type: "Museum",
//     country: "United States",
//   },
//   { name: "Fallingwater", type: "Historic Site", country: "United States" },
//   {
//     name: "American Girl Place",
//     type: "Entertainment",
//     country: "United States",
//   },
//   {
//     name: "Grand Canyon Skywalk",
//     type: "Observation Deck",
//     country: "United States",
//   },
//   { name: "Newport Mansions", type: "Historic Site", country: "United States" },
//   { name: "Epcot", type: "Theme Park", country: "United States" },
//   {
//     name: "San Francisco Museum of Modern Art",
//     type: "Art Gallery",
//     country: "United States",
//   },
//   { name: "The Getty Villa", type: "Museum", country: "United States" },
//   {
//     name: "The National Shrine of the Immaculate Conception",
//     type: "Historic Site",
//     country: "United States",
//   },
//   {
//     name: "Museum of the City of New York",
//     type: "Museum",
//     country: "United States",
//   },
//   {
//     name: "Astroville Underground Tour",
//     type: "Historic Site",
//     country: "United States",
//   },
//   {
//     name: "Santa Barbara Mission",
//     type: "Historic Site",
//     country: "United States",
//   },
//   { name: "Lincoln Park Zoo", type: "Zoo", country: "United States" },
//   { name: "Tennessee Aquarium", type: "Aquarium", country: "United States" },
//   {
//     name: "Boston Children's Museum",
//     type: "Museum",
//     country: "United States",
//   },
//   {
//     name: "Everglades National Park",
//     type: "National Park",
//     country: "United States",
//   },
//   { name: "Georgia Aquarium", type: "Aquarium", country: "United States" },
//   {
//     name: "Smithsonian National Air and Space Museum",
//     type: "Museum",
//     country: "United States",
//   },
//   { name: "Old Faithful", type: "Natural Wonder", country: "United States" },
//   { name: "Cedar Point", type: "Theme Park", country: "United States" },
//   { name: "Boston Common", type: "Park", country: "United States" },
//   { name: "The High Line", type: "Park", country: "United States" },
//   { name: "The Broad Museum", type: "Art Gallery", country: "United States" },
//   { name: "MoMA PS1", type: "Art Gallery", country: "United States" },
//   { name: "Magic Kingdom", type: "Theme Park", country: "United States" },
//   { name: "Central Park Zoo", type: "Zoo", country: "United States" },
//   { name: "The British Museum", type: "Museum", country: "United Kingdom" },
//   {
//     name: "The Tower of London",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   { name: "Buckingham Palace", type: "Landmark", country: "United Kingdom" },
//   {
//     name: "The London Eye",
//     type: "Observation Wheel",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Houses of Parliament",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   { name: "The Tate Modern", type: "Art Gallery", country: "United Kingdom" },
//   {
//     name: "The Natural History Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Victoria and Albert Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   { name: "The Shard", type: "Skyscraper", country: "United Kingdom" },
//   {
//     name: "Westminster Abbey",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   {
//     name: "St. Paul's Cathedral",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   { name: "The London Zoo", type: "Zoo", country: "United Kingdom" },
//   { name: "The Science Museum", type: "Museum", country: "United Kingdom" },
//   {
//     name: "The Royal Observatory",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   {
//     name: "The National Gallery",
//     type: "Art Gallery",
//     country: "United Kingdom",
//   },
//   { name: "Kew Gardens", type: "Botanical Garden", country: "United Kingdom" },
//   { name: "The British Library", type: "Library", country: "United Kingdom" },
//   { name: "Camden Market", type: "Market", country: "United Kingdom" },
//   { name: "Natural History Museum", type: "Museum", country: "United Kingdom" },
//   { name: "Covent Garden", type: "Market", country: "United Kingdom" },
//   {
//     name: "The London Dungeon",
//     type: "Entertainment",
//     country: "United Kingdom",
//   },
//   { name: "London Aquarium", type: "Aquarium", country: "United Kingdom" },
//   { name: "Madame Tussauds", type: "Museum", country: "United Kingdom" },
//   { name: "Hyde Park", type: "Park", country: "United Kingdom" },
//   { name: "Regent's Park", type: "Park", country: "United Kingdom" },
//   { name: "Greenwich Park", type: "Park", country: "United Kingdom" },
//   { name: "The Serpentine", type: "Lake", country: "United Kingdom" },
//   { name: "The Monument", type: "Landmark", country: "United Kingdom" },
//   {
//     name: "The Royal Albert Hall",
//     type: "Concert Hall",
//     country: "United Kingdom",
//   },
//   {
//     name: "Shakespeare's Globe Theatre",
//     type: "Theatre",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Churchill War Rooms",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   { name: "Trafalgar Square", type: "Landmark", country: "United Kingdom" },
//   { name: "Southbank Centre", type: "Arts Centre", country: "United Kingdom" },
//   {
//     name: "London Transport Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   { name: "The London Film Museum", type: "Museum", country: "United Kingdom" },
//   { name: "The Old Bailey", type: "Historic Site", country: "United Kingdom" },
//   { name: "The Design Museum", type: "Museum", country: "United Kingdom" },
//   { name: "Somerset House", type: "Historic Site", country: "United Kingdom" },
//   {
//     name: "The Imperial War Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   { name: "The Geffrye Museum", type: "Museum", country: "United Kingdom" },
//   { name: "The Foundling Museum", type: "Museum", country: "United Kingdom" },
//   {
//     name: "The Wellcome Collection",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   { name: "The Royal Mews", type: "Historic Site", country: "United Kingdom" },
//   { name: "The Queen's Walk", type: "Walk", country: "United Kingdom" },
//   { name: "St. James's Park", type: "Park", country: "United Kingdom" },
//   {
//     name: "The Royal Exchange",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Barbican Centre",
//     type: "Arts Centre",
//     country: "United Kingdom",
//   },
//   { name: "The Museum of London", type: "Museum", country: "United Kingdom" },
//   {
//     name: "The Courtauld Gallery",
//     type: "Art Gallery",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Handel & Hendrix in London",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Sherlock Holmes Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   {
//     name: "The London Eye River Cruise",
//     type: "Cruise",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Sky Garden",
//     type: "Observation Deck",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Royal Academy of Arts",
//     type: "Art Gallery",
//     country: "United Kingdom",
//   },
//   {
//     name: "The South London Gallery",
//     type: "Art Gallery",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Fashion and Textile Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   {
//     name: "The London Wetland Centre",
//     type: "Nature Reserve",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Victoria Embankment Gardens",
//     type: "Park",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Chelsea Physic Garden",
//     type: "Botanical Garden",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Golden Hinde",
//     type: "Historic Ship",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Tower Bridge Exhibition",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Museum of London Docklands",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   {
//     name: "The London Motorcycle Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Dennis Severs' House",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   { name: "The Crystal Palace Park", type: "Park", country: "United Kingdom" },
//   {
//     name: "The London Buddhist Centre",
//     type: "Cultural Site",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Bargehouse",
//     type: "Exhibition Space",
//     country: "United Kingdom",
//   },
//   { name: "The O2 Arena", type: "Entertainment", country: "United Kingdom" },
//   { name: "The Cutty Sark", type: "Historic Ship", country: "United Kingdom" },
//   {
//     name: "The Black Cultural Archives",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Old Royal Naval College",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Queen's Walkway",
//     type: "Walking Trail",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Tower of London",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   { name: "The London Palladium", type: "Theatre", country: "United Kingdom" },
//   {
//     name: "The Royal Observatory",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   {
//     name: "The National Portrait Gallery",
//     type: "Art Gallery",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Florence Nightingale Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Sir John Soane's Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   { name: "The Horniman Museum", type: "Museum", country: "United Kingdom" },
//   { name: "The Museum of Brands", type: "Museum", country: "United Kingdom" },
//   {
//     name: "The Science and Media Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Natural History Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   { name: "The Hunterian Museum", type: "Museum", country: "United Kingdom" },
//   { name: "The Tate Britain", type: "Art Gallery", country: "United Kingdom" },
//   {
//     name: "The Royal National Theatre",
//     type: "Theatre",
//     country: "United Kingdom",
//   },
//   {
//     name: "The London Design Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   { name: "The Museum of London", type: "Museum", country: "United Kingdom" },
//   {
//     name: "The Churchill War Rooms",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   {
//     name: "The South London Botanical Institute",
//     type: "Botanical Garden",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Whitechapel Gallery",
//     type: "Art Gallery",
//     country: "United Kingdom",
//   },
//   { name: "The Museum of the Home", type: "Museum", country: "United Kingdom" },
//   {
//     name: "The Southwark Cathedral",
//     type: "Historic Site",
//     country: "United Kingdom",
//   },
//   {
//     name: "The London Fire Brigade Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   { name: "The Foundling Museum", type: "Museum", country: "United Kingdom" },
//   {
//     name: "The London School of Economics Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Wilton's Music Hall",
//     type: "Music Hall",
//     country: "United Kingdom",
//   },
//   { name: "The Geffrye Museum", type: "Museum", country: "United Kingdom" },
//   { name: "The Royal Mint Museum", type: "Museum", country: "United Kingdom" },
//   {
//     name: "The British Film Institute",
//     type: "Film Institute",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Museum of London Docklands",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   {
//     name: "The Victoria and Albert Museum",
//     type: "Museum",
//     country: "United Kingdom",
//   },
//   {
//     name: "The London Aquatics Centre",
//     type: "Sports Centre",
//     country: "United Kingdom",
//   },
//   { name: "The Soho Theatre", type: "Theatre", country: "United Kingdom" },
//   { name: "The Harrods", type: "Department Store", country: "United Kingdom" },
//   {
//     name: "The London Philharmonic Orchestra",
//     type: "Music",
//     country: "United Kingdom",
//   },
// ];
